stages:
  # build
  # test
  - release

cache:
  paths:  
  - node_modules/   

release:
  before_script:
    - npm install
  image: node:8
  only:
    - dev@batman/batman
  script:
    - $(npm bin)/semantic-release-gitlab
  stage: release