image: node:8.0.0

cache:
  paths:  
  - node_modules/   

build:
  stage: build
  script:
    - apt-get install ruby-full
    - gem install sass
    - npm config set proxy http://194.138.0.4:9400/
    - npm config set https-proxy http://194.138.0.4:9400/
    - npm run setup

