image: node:8.0.0

cache:
    paths:
    - node/modules/
    
cache:
  paths:  
  - node_modules/   

build:
  stage: build
  script:
    - npm install
    - npm run e2e-setup
test:
  stage: test
  script:
    - npm run e2e
